### PR TITLE
Fix some import errors due to a PEP-8 fix in platform.

### PR DESCRIPTION
**Pull request by rbarlow**
This must be merged before https://github.com/pulp/pulp/pull/1703.

### CODE REVIEW

**Comment by beav** [comment]
Can you add `blinker` to `travis-setup.sh`? This is not related to your change but will fix the unit tests when run by travis.

**Comment by rbarlow** [comment]
I added blinker, so it should be ready for re-review (assuming Travis is cool with it).

**Comment by rbarlow** [comment]
Travis is cool with it, so this is ready to be re-reviewed. Thanks!

**Comment by beav** [comment]
LGTM

**Pull request merged**
